apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: redis-server
  description: Redis Server App
  tags:
    - nosql
    - redis
  annotations:
    'backstage.io/kubernetes-label-selector': 'app=redis-server,tier=cache'
spec:
  type: service
  lifecycle: experimental
  owner: team-a
  system: yelb
